name: gemgis_dev_env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  # geopandas will also install numpy, pandas, shapely, fiona, and pyproj
  - geopandas>=0.14.0
  # rasterio will also install affine
  #- rasterio>=1.3.8 will be installed through rioxarray
  # pyvista also install pooch and matplotlib
  #- pyvista>=0.42.2 will be installed through pvgeo
  - gemgis>=1.1
  - gempy>=2.3
  - rioxarray
  - PVGeo
  - scipy
  - owslib
  - scikit-image
  - mplstereonet
  - PyPDF2
  - xmltodict
  - geopy
  - scikit-learn
  - tqdm
  - requests
  - pooch<1.5.0
  - pyqt5
  - nbsphinx
  - sphinx_markdown_tables
  - sphinx_gallery
  - sphinx_rtd_theme
  - sphinx_book_theme==0.3.3
  - sphinx_copybutton
  - sphinx_automodapi
  - sphinx_numfig
  - numpydoc
  - build
