name: gemgis_dev_env
channels:
  - conda-forge
dependencies:
  #- python>=3.7
  #- pygeos=0.9
  #- geopandas
  #- rasterio
  #- pyvista
  - pip
  - pip:
    - gemgis
    - matplotlib
    - pandas
    - pooch<1.5.0
   # - gempy==2.2.9
    - pyqt5
    - nbsphinx
    - sphinx_markdown_tables
    - sphinx_gallery
    - sphinx_rtd_theme
    - sphinx_copybutton
    - sphinx_automodapi
    - sphinx_numfig
    - numpydoc
