name: GemGIS CI

on:
  push:
    branches: [ master, dev_aj, dev_alex ]

  pull_request:
    branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  testing:
    name: Testing
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gemgis_testing
          environment-file: environment.yml
          python-version: 3.9
          channels: conda-forge
      - name: List dependencies
        run: |
          conda list pygeos
          conda list geopandas
          conda list rasterio
          conda list pyvista
          conda list gemgis
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_optional.txt
          pip install gemgis
      - name: Run tests with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest